name: Transpile for Node branch

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup Repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Deno Lint
        run: deno lint
        
      - name: Build npm folder
        run: deno run -A --unstable ./scripts/dnt.ts
        
      - name: Add .gitignore
        run: echo node_modules/ > "npm/.gitignore"
        
      - name: Push to Node branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: node
          FOLDER: npm
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"